<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            font-family: sans-serif;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 9px;
            text-align: center;
            color: #888;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Schedule Report</h1>
        <h3>{{ $semester->name }} - {{ ucfirst($semester->type) }}</h3>
        <p>Generated on {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Course</th>
                <th>Sec #</th>
                <th>Instructor</th>
                <th>Days</th>
                <th>Time</th>
                <th>Room</th>
                <th>Credit Hours</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sections as $section)
                <tr>
                    <td>
                        <strong>{{ $section->course->code }}</strong><br>
                        {{ $section->course->name }}
                    </td>
                    <td>{{ $section->section_number }}</td>
                    <td>{{ $section->instructor->user->name ?? 'TBA' }}</td>
                    <td>{{ is_array($section->days) ? implode(', ', $section->days) : $section->days }}</td>
                    <td>
                        {{ \Carbon\Carbon::parse($section->start_time)->format('H:i') }} -
                        {{ \Carbon\Carbon::parse($section->end_time)->format('H:i') }}
                    </td>
                    <td>{{ $section->room->name ?? 'TBA' }}</td>
                    <td>{{ $section->course->credits ?? 3 }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Fathi Al-Sadi
    </div>
</body>

</html>
